### PR TITLE
[TASK] Hardware images for routers on the map

### PR DESCRIPTION
**Pull request by maurerle**
## Description
This adds the option to set an url where hardware images can be fetched from.

These are then shown per router, as can be seen here:

image

## Motivation and Context
This is a very nice feature which is available in hopglass but wasn't available in meshviewer until now.
It helps to recognize how the router looks like.

To create an image source, one can either use existing ones like:
`https://cdn.rawgit.com/Moorviper/meshviewer_hwpics/master/nodes/{MODEL_HASH}.svg`
`https://map.eulenfunk.de/nodes/{MODEL_HASH}.svg`
or a [bash script as described here](https://forum.freifunk.net/t/mithilfe-aufruf-aktuelle-firmware-selector-bilder/23821/4)
`https://map.aachen.freifunk.net/router-images/{MODEL_NORMALIZED}.svg`

## How Has This Been Tested?
This patchset is currently active in Aachen, see:
https://map.aachen.freifunk.net

## Checklist:
- [ ] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by skorpy2009** [comment]
Is this compatible with https://github.com/freifunk-darmstadt/gluon-firmware-selector/tree/master/pictures ?

**Comment by maurerle** [comment]
@skorpy2009 it basically is, but some routers have different names than model_normalized on the firmware selector.
Furthermore the firmware selector is missing some newer images.

For a full list of needed aliases, take a look at my post in the freifunk forum:
https://forum.freifunk.net/t/mithilfe-aufruf-aktuelle-firmware-selector-bilder/23821/4

I would like to have a repo with svg images in a freifunk-org which is used for both applications as a source..

**Comment by MyIgel** [comment]
Having some "single point of truth" would be definitely nice & to accommodate for the different naming schemes we could imho either create a mapping (static or calculated) or (eventually better) implement the slug generator in JS?

**Comment by MyIgel** [comment]
(Also regarding the visuals: Imho it would make the whole view more "coherent" if the image would be centred as it currently looks like something is missing on the right of it)

**Comment by maurerle** [comment]
Thanks, I added css accordingly and moved it into a separated css class

**Pull request merged**
