### PR TITLE
[TASK] Merge freifunkstuff

### PR DESCRIPTION
**Pull request by maurerle**
## Description
merges changes from https://github.com/freifunkstuff/meshviewer
  * Dockerfile
  * Hardware Images for routers
  * support for embedding
  * show total client count in mesh cloud
  * support for links
  * different icon color if has vpn

## Motivation and Context
This change is needed to contribute changes to the meshviewer "upstream".
So that one can have HwImg and deprecation warnings at the same time

## How Has This Been Tested?

```
docker build -t meshviewer .
docker run -v ./config.json:/usr/share/nginx/html/config.json -p 8088:80 meshviewer
```

## Screenshots/links (if appropriate):

image

## Checklist:

- [ ] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by maurerle** [comment]
I would need some help to see why the uglify is unhappy:

```
5.469 [20:48:12] Optimizing app.js
6.131 Error: Cannot uglify file: ../node_modules/almond/almond.build.js. Skipping it. Error is:
6.131 SyntaxError: Unexpected token operator «=», expected punc «,»
6.131 
6.131 If the source uses ES2015 or later syntax, please pass "optimize: 'none'" to r.js and use an ES2015+ compatible minifier after running r.js. The included UglifyJS only understands ES5 or earlier syntax.
6.340 [20:48:13] 'javascript' errored after 1.43 s
6.340 [20:48:13] GulpUglifyError: unable to minify JavaScript
6.340 Caused by: SyntaxError: Unexpected token: operator «=», expected: punc «,»
6.340 File: app.js
6.340 Line: 3287
6.340 Col: 36
6.340 [20:48:13] 'default' errored after 5.31 s
```

Maybe we need to update dependencies..?

**Comment by maurerle** [comment]
I also created a script, which generates a correctly named output-folder for router images:
https://forum.freifunk.net/t/mithilfe-aufruf-aktuelle-firmware-selector-bilder/23821/4

The created folder can then be served with the hwImg setting set to `https://servername/router-images/{MODEL_NORMALIZED}.svg`

It would be great if there would be one common source for this and the firmware-selector:
https://github.com/freifunk-darmstadt/gluon-firmware-selector/issues/154

**Comment by maurerle** [comment]
@skorpy2009  should I split this up into a PR or commit for each of the features?

* Dockerfile
* Hardware Images for routers
* support for embedding
* show total client count in mesh cloud
* support for links
* different icon color if has vpn

**Comment by maurerle** [comment]
This PR is superseded by the splitted ones referenced in #28 - I hope that this helpes to integrate changes upstream.

**Comment by MyIgel** [comment]
Definietly: having single-feature-PRs is the better way to go.
(And on the long run we should find a group of ppl that are able to maintain the software stack in a "new" group together ^^)

**Pull request closed without merging**
