### PR TITLE
[BUGFIX] Allow defining gejson in config.json

### PR DESCRIPTION
**Pull request by maurerle**
## Description
This was not yet fixed for using the json instead of a js file.
It works now, for example by adding the following to the config.json:
```
"geo": [
  {
    "json": [
      {
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                12.04925537109375,
                49.036517514836994
              ],
              [
                12.033462524414062,
                49.021660359632115
              ],
              [
                12.058181762695312,
                48.99553703238219
              ],
              [
                12.11311340332031,
                49.001843917978526
              ],
              [
                12.122726440429686,
                49.03381654386847
              ],
              [
                12.04925537109375,
                49.036517514836994
              ]
            ]
          ]
        }
      }
    ],
    "option": {
      "style": {
        "color": "#e23535",
        "weight": 5,
        "opacity": 0.4,
        "fillColor": "#6de922",
        "fillOpacity": 0.1
      }
    }
  }
],
```

## Motivation and Context

This allows to define polygons as overlay for borders

## How Has This Been Tested?

Define the given snippet in the config.json

## Screenshots/links (if appropriate):
image

## Checklist:

- [ ] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by genofire** [comment]
I believe that does not allow to load external geojson any more, like the following:

```javascript
geo': [{
      'json': function() {
        return require('helper').getJSON('/map/breminale.geojson')
      },
      'option': {
        'pointToLayer': function (feature, latlng) {
          return L.circleMarker(latlng, {
            radius: 8,
            fillColor: feature.properties['marker-color'] ? feature.properties['marker-color']: feature.color,
            color: '#ffa500',
            weight: 1,
            opacity: 1,
            fillOpacity: 0.8
          })
          // .bindTooltip(feature.properties.name ? feature.properties.name.toString() : '');
        },
        pane: 'markerPane',
        onEachFeature: function (feature, layer) {
          layer.bindTooltip(feature.properties.name ? feature.properties.name.toString() : '')
        },
      }
    }],
```

**Comment by maurerle** [comment]
Thanks, that was exactly what I needed! :)

**Comment by maurerle** [comment]
I wanted to validate your example, but you can't store functions in a config.json -> wou would either have to do something like this:
https://stackoverflow.com/a/47558227
or stringify it.


So to support loading from a file, we need more client code in this fork.

**Comment by genofire** [comment]
@maurerle i am not sure, why in this fork is an config.json in statt of an config.js in example (like in origin / ffrgb) ...

**Comment by MyIgel** [comment]
The answer is easy: because it was changed in 102c8af8734f506fe6448377d249d1ab21832d1e ;)
(and thats most probably because it is cleaner that way by not having static (JSON) and dynamic (JS) configs merged)

**Pull request closed without merging**
